default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/petfinder.sqlite3

production:
  <<: *default
  database: db/petfinder.sqlite3

steve:
  <<: *default
  database: db/petfinder.sqlite3
